version: "3.9"
   
services:
  backend:
    build:
      context: ./build
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    environment:
      - BASE_URL=${BASE_URL}
      - CONNECTION_STRING=${CONNECTION_STRING}
